version: '3.8'
services:
  reader-connector:
    build: .
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "8086:8086"
    volumes:
      - ../:/reader-connector
      - ~/.gitconfig:/root/.gitconfig:z
    stdin_open: true
    tty: true
    restart: unless-stopped
